In [25]:
import pandas as pd
import numpy as np

df = pd.read_csv("../csv/F1_4_Detailed releases at facility level with E-PRTR Sector and Annex I Activity detail into Air.csv")

In [26]:
df.head()

,countryName,EPRTRSectorCode,eprtrSectorName,EPRTRAnnexIMainActivityCode,EPRTRAnnexIMainActivityLabel,FacilityInspireID,facilityName,Longitude,Latitude,City,targetRelease,pollutant,emissions,reportingYear
0,Austria,4,Chemical industry,4(d),Chemical installations for the production on a...,AT.CAED/9008390392737.FACILITY,Nufarm GmbH & CO KG,14.336056,48.290943,Linz,AIR,"1,2-dichloroethane (DCE-1,2)",3300.0,2007
1,Austria,9,Other activities,9(c),Installations for the surface treatment of sub...,AT.CAED/9008390396414.FACILITY,MAGNA STEYR Fahrzeugtechnik AG&Co KG,15.477778,47.019170,"Graz,07.Bez.:Liebenau",AIR,Non-methane volatile organic compounds (NMVOC),170000.0,2007
2,Austria,6,Paper and wood production and processing,6(b),Industrial plants for the production of paper ...,AT.CAED/9008390397176.FACILITY,Fritz EGGER GmbH & Co. OG,15.691833,48.259556,Unterradlberg,AIR,Carbon dioxide (CO2),228000000.0,2007
3,Austria,6,Paper and wood production and processing,6(b),Industrial plants for the production of paper ...,AT.CAED/9008390397176.FACILITY,Fritz EGGER GmbH & Co. OG,15.691833,48.259556,Unterradlberg,AIR,Nitrogen oxides (NOX),311000.0,2007
4,Austria,3,Mineral industry,3(c),Installations for the production of cement cli...,AT.CAED/9008390397220.FACILITY,voestalpine Stahl GmbH,14.159778,47.807083,Klaus an der Pyhrnbahn,AIR,Carbon dioxide (CO2),329000000.0,2007

In [27]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288566 entries, 0 to 288565
Data columns (total 14 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   countryName                   288566 non-null  object
 1   EPRTRSectorCode               288566 non-null  int64
 2   eprtrSectorName               288566 non-null  object
 3   EPRTRAnnexIMainActivityCode   288566 non-null  object
 4   EPRTRAnnexIMainActivityLabel  288566 non-null  object
 5   FacilityInspireID             288566 non-null  object
 6   facilityName                  288547 non-null  object
 7   Longitude                     288566 non-null  float64
 8   Latitude                      288566 non-null  float64
 9   City                          288342 non-null  object
 10  targetRelease                 288566 non-null  object
 11  pollutant                     288566 non-null  object
 12  emissions                     288566 non-null  float64
 13  reportingYear                 288566 non-null  int64
dtypes: float64(3), int64(2), object(9)
memory usage: 30.8+ MB
None

In [28]:
df.describe()

,EPRTRSectorCode,Longitude,Latitude,emissions,reportingYear
count,288566.000000,288566.000000,288566.000000,2.885660e+05,288566.000000
mean,4.205239,7.248907,48.293419,9.502748e+07,2013.016676
std,2.513370,10.538875,6.933106,6.984015e+08,3.891024
min,1.000000,-63.080350,-21.303590,0.000000e+00,2007.000000
25%,1.000000,-0.915578,43.575665,1.160000e+04,2010.000000
50%,4.000000,6.709500,49.210195,4.120000e+04,2013.000000
75%,7.000000,14.574320,52.211600,4.950000e+05,2016.000000
max,9.000000,55.666840,76.597755,4.320000e+10,2020.000000

In [29]:
df.isna().sum()

countryName                       0
EPRTRSectorCode                   0
eprtrSectorName                   0
EPRTRAnnexIMainActivityCode       0
EPRTRAnnexIMainActivityLabel      0
FacilityInspireID                 0
facilityName                     19
Longitude                         0
Latitude                          0
City                            224
targetRelease                     0
pollutant                         0
emissions                         0
reportingYear                     0
dtype: int64

In [30]:
df["City"] = df["City"].fillna("papapapapa")

In [31]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="myApp")

In [32]:
for i in range(len(df)): 
    if df.loc[i, "City"] == "papapapapa":
        latitude = df.loc[i, "Latitude"]
        longitude = df.loc[i, "Longitude"]
        coord = str(latitude) + ", " + str(longitude)
        location = geolocator.reverse(coord,language='en')
        loc_dict = location.raw
        if ("city" in loc_dict["address"].keys()): df.loc[i, "City"] = loc_dict["address"]["city"]
        elif ("town" in loc_dict["address"].keys()): df.loc[i, "City"] = loc_dict["address"]["town"]
        elif ("village" in loc_dict["address"].keys()): df.loc[i, "City"] = loc_dict["address"]["village"]

In [33]:
for i in range(len(df)): 
    if df.loc[i, "City"] == "papapapapa":
        df.loc[i, "City"] = ""

In [34]:
df.head()

,countryName,EPRTRSectorCode,eprtrSectorName,EPRTRAnnexIMainActivityCode,EPRTRAnnexIMainActivityLabel,FacilityInspireID,facilityName,Longitude,Latitude,City,targetRelease,pollutant,emissions,reportingYear
0,Austria,4,Chemical industry,4(d),Chemical installations for the production on a...,AT.CAED/9008390392737.FACILITY,Nufarm GmbH & CO KG,14.336056,48.290943,Linz,AIR,"1,2-dichloroethane (DCE-1,2)",3300.0,2007
1,Austria,9,Other activities,9(c),Installations for the surface treatment of sub...,AT.CAED/9008390396414.FACILITY,MAGNA STEYR Fahrzeugtechnik AG&Co KG,15.477778,47.019170,"Graz,07.Bez.:Liebenau",AIR,Non-methane volatile organic compounds (NMVOC),170000.0,2007
2,Austria,6,Paper and wood production and processing,6(b),Industrial plants for the production of paper ...,AT.CAED/9008390397176.FACILITY,Fritz EGGER GmbH & Co. OG,15.691833,48.259556,Unterradlberg,AIR,Carbon dioxide (CO2),228000000.0,2007
3,Austria,6,Paper and wood production and processing,6(b),Industrial plants for the production of paper ...,AT.CAED/9008390397176.FACILITY,Fritz EGGER GmbH & Co. OG,15.691833,48.259556,Unterradlberg,AIR,Nitrogen oxides (NOX),311000.0,2007
4,Austria,3,Mineral industry,3(c),Installations for the production of cement cli...,AT.CAED/9008390397220.FACILITY,voestalpine Stahl GmbH,14.159778,47.807083,Klaus an der Pyhrnbahn,AIR,Carbon dioxide (CO2),329000000.0,2007

In [38]:
df = df.drop(columns=["facilityName", "eprtrSectorName", "EPRTRAnnexIMainActivityLabel"])

In [39]:
df.head()

,countryName,EPRTRSectorCode,EPRTRAnnexIMainActivityCode,FacilityInspireID,Longitude,Latitude,City,targetRelease,pollutant,emissions,reportingYear
0,Austria,4,4(d),AT.CAED/9008390392737.FACILITY,14.336056,48.290943,Linz,AIR,"1,2-dichloroethane (DCE-1,2)",3300.0,2007
1,Austria,9,9(c),AT.CAED/9008390396414.FACILITY,15.477778,47.019170,"Graz,07.Bez.:Liebenau",AIR,Non-methane volatile organic compounds (NMVOC),170000.0,2007
2,Austria,6,6(b),AT.CAED/9008390397176.FACILITY,15.691833,48.259556,Unterradlberg,AIR,Carbon dioxide (CO2),228000000.0,2007
3,Austria,6,6(b),AT.CAED/9008390397176.FACILITY,15.691833,48.259556,Unterradlberg,AIR,Nitrogen oxides (NOX),311000.0,2007
4,Austria,3,3(c),AT.CAED/9008390397220.FACILITY,14.159778,47.807083,Klaus an der Pyhrnbahn,AIR,Carbon dioxide (CO2),329000000.0,2007

In [40]:
df["targetRelease"].unique()

array(['AIR'], dtype=object)

In [42]:
df = df.drop(columns=["targetRelease"])

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288566 entries, 0 to 288565
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   countryName                  288566 non-null  object
 1   EPRTRSectorCode              288566 non-null  int64
 2   EPRTRAnnexIMainActivityCode  288566 non-null  object
 3   FacilityInspireID            288566 non-null  object
 4   Longitude                    288566 non-null  float64
 5   Latitude                     288566 non-null  float64
 6   City                         288566 non-null  object
 7   pollutant                    288566 non-null  object
 8   emissions                    288566 non-null  float64
 9   reportingYear                288566 non-null  int64
dtypes: float64(3), int64(2), object(5)
memory usage: 22.0+ MB

In [44]:
df = df.assign(Air=1)
df = df.assign(Water=0)

In [45]:
df.head()

,countryName,EPRTRSectorCode,EPRTRAnnexIMainActivityCode,FacilityInspireID,Longitude,Latitude,City,pollutant,emissions,reportingYear,Air,Water
0,Austria,4,4(d),AT.CAED/9008390392737.FACILITY,14.336056,48.290943,Linz,"1,2-dichloroethane (DCE-1,2)",3300.0,2007,1,0
1,Austria,9,9(c),AT.CAED/9008390396414.FACILITY,15.477778,47.019170,"Graz,07.Bez.:Liebenau",Non-methane volatile organic compounds (NMVOC),170000.0,2007,1,0
2,Austria,6,6(b),AT.CAED/9008390397176.FACILITY,15.691833,48.259556,Unterradlberg,Carbon dioxide (CO2),228000000.0,2007,1,0
3,Austria,6,6(b),AT.CAED/9008390397176.FACILITY,15.691833,48.259556,Unterradlberg,Nitrogen oxides (NOX),311000.0,2007,1,0
4,Austria,3,3(c),AT.CAED/9008390397220.FACILITY,14.159778,47.807083,Klaus an der Pyhrnbahn,Carbon dioxide (CO2),329000000.0,2007,1,0

In [47]:
df.to_csv("F1_4_clean_data.csv")

Au final pas sûr que ça soit intéressant de garder les villes vu qu'on a les longitudes et latitudes